language: dart

dart:
  - dev
  - 2.1.0

dart_task:
  - test
  - dartfmt
  - dartanalyzer: --fatal-infos --fatal-warnings .

# Only building master means that we don't run two builds for each pull request.
branches:
  only: [master]

cache:
  directories:
    - $HOME/.pub-cache
