include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - unnecessary_await_in_return
