include: package:dart_flutter_team_lints/analysis_options.yaml

analyzer:
  language:
    strict-inference: true
    strict-casts: true

linter:
  rules:
    - avoid_returning_null
    - avoid_returning_null_for_future
    - avoid_unused_constructor_parameters
    - cancel_subscriptions
    - comment_references
    - literal_only_boolean_expressions
    - no_adjacent_strings_in_list
    - package_api_docs
    - prefer_const_constructors
    - test_types_in_equals
    - unnecessary_await_in_return
